- hosts: myservers
  become: yes
  vars:
   var1: "{{ var1 }}"
   var2: "{{ var2 }}"
  tasks:
  - name: Adding user {{ var1 }}
    user:
     name: "{{ var1 }}"
     shell: /bin/false
  - name: adding file {{ var2 }} in tmp
    file:
     name: "{{ var2 }}"
     state: touch
 
